// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/.well-known/lnurlp/[name].ts";
import * as $1 from "./routes/[name].tsx";
import * as $2 from "./routes/address/[name].ts";
import * as $3 from "./routes/callback/[name].ts";
import * as $4 from "./routes/index.ts";
import * as $$0 from "./islands/SendLn.tsx";
import * as $$1 from "./islands/SendOnChain.tsx";

const manifest = {
  routes: {
    "./routes/.well-known/lnurlp/[name].ts": $0,
    "./routes/[name].tsx": $1,
    "./routes/address/[name].ts": $2,
    "./routes/callback/[name].ts": $3,
    "./routes/index.ts": $4,
  },
  islands: {
    "./islands/SendLn.tsx": $$0,
    "./islands/SendOnChain.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
